### ISSUE TITLE
[High priority] MySQL Connections not closed

### ISSUE THREAD

**Issue by korhox** [storm345/ServerAssistantIssues#3]
@storm345 

Hi. I have this problem:
Server Assistant seems not to close MySQL-connections and my service provider contacted me with their issue, that MySQL-server users can not use their services, because I have 120 open connections to database, where Server Assistant is used. No other plugins are logging their data to database as aggressively.

**Comment by storm345** [comment]
Hey,

I have looked into this and identified that this is indeed an issue - the line of code to close the connection to the database had been erroneously omitted and for that I apologize. I have fixed the issue and you can now download the fixed version from spigotmc.org using the following link:

https://www.spigotmc.org/resources/server-assistant-automatic-issue-reporter-and-handler-report-errors-lag-and-crashes-with-cause.28664/update?update=208483

Thank you for finding and reporting this issue. 

-Eddie

**Comment by korhox** [comment]
Thank you for fast response and fix! 5/5 stars!
