### ISSUE TITLE
SSL-based error

### ISSUE THREAD

**Issue by korhox** [storm345/ServerAssistantIssues#4]
Hi!
I'm having this issue. I tried to add this to config, but it seems it does not work.
`useSSL:false`

This short error is spammed to console, as seen below:

> [00:44:15] [pool-12-thread-1/INFO]: [ServerAssistant] Saved information about ERROR to archive!
> [00:44:16] [pool-12-thread-1/WARN]: Mon Jun 18 00:44:16 EEST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
> [00:44:16] [pool-12-thread-1/INFO]: [ServerAssistant] SQL Error: Duplicate entry 'FlosMine-ERROR-2018-06-18 00:44:16' for key 'PRIMARY' State: 23000 Code: 1062
> [00:44:16] [pool-12-thread-1/WARN]: Mon Jun 18 00:44:16 EEST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
> [00:44:17] [pool-12-thread-1/INFO]: [ServerAssistant] Saved information about ERROR to archive!
> [00:44:17] [pool-12-thread-1/WARN]: Mon Jun 18 00:44:17 EEST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
> [00:44:17] [pool-12-thread-1/INFO]: [ServerAssistant] SQL Error: Duplicate entry 'FlosMine-ERROR-2018-06-18 00:44:17' for key 'PRIMARY' State: 23000 Code: 1062
> [00:44:17] [pool-12-thread-1/WARN]: Mon Jun 18 00:44:17 EEST 2018 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.

Am I made mistake or is this about plugin?

I can provide latest.log and config file privately.

**Comment by storm345** [comment]
This issue is caused by the SQL library not liking that you are connecting to your database insecurely, which causes an error, which server assistant catches and tries to log to SQL which in turn causes the error again, etc... Adding useSSL=false to the config will not work as the config being referred to by the error message is one internal and not one you can access. The best way to fix this would be to connect to your database securely (by changing your config so that the error doesn't occur). To make it possible to allow insecure connections would require a code change (which can be done, but am not availabile to do it for at least a few days). If you can provide configs privately that would be helpful.

**Comment by korhox** [comment]
Hi,

I sent my config file trough email.

**Comment by storm345** [comment]
Okay. Two fixes: Option 1 is make sure exception detector is set to 'uncaught only' or if that doesn't work is disabled, option 2 is you try the new build of ServerAssistant 1.0.11 which I am uploading today which has a useSSL option in the config (which you should set to false to fix the issue)

**Comment by storm345** [comment]
You can download 1.0.11 here: https://www.spigotmc.org/resources/server-assistant-automatic-issue-reporter-and-handler-report-errors-lag-and-crashes-with-cause.28664/update?update=230526

Please get back to me with regards to whether this fixes the issue so that this ticket can be closed.

**Comment by korhox** [comment]
Yes this fixed the issue! Thank you for fast help!
