### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by fyxisShazad** [storm345/ServerAssistantIssues#6]
When update will be posted?

**Comment by storm345** [comment]
Hi! The latest version I have just checked on 1.16 and it all works so I have updated the resource page to show that it is compatible with 1.16. (The plugin is built on top of pretty stable API that doesn't typically change between versions and so is unlikely to break with version updates)

**Comment by fyxisShazad** [comment]
Is there way you can help me configure it to send sms or use discord webhook when crash happend on my server? and if its free?

I use version from spigotmc not cracked one

**Comment by storm345** [comment]
You should be able to setup those via an IFTTT hook in the plugin config.

Details for how to configure the plugin to trigger an IFTTT hook:
http://storm345.github.io/ServerAssistant/configuringIssueResponses.html#IFTTT

SMS IFTTT hooks:
https://ifttt.com/sms

For setting up IFTTT to post to discord there are a few guides online, here is one of them:
https://gist.github.com/DerEnderKeks/6448c28f5e32b4b52741fbda4ec34285

Hopefully this helps you :)
