### ISSUE TITLE
Error with ifttt

### ISSUE THREAD

**Issue by MrMcyeet** [storm345/ServerAssistantIssues#8]
I just bought this plugin, and im sure ive set something up wrong, but i cannot figure out what.

I started my test server, and ran `/lagit`, and the plugin seemed to *try* to do something, but came back saying something about a response code 413, which i think means that the request sent was too large, but i could be wrong about that.

Here is the server log from what happened.
https://pastebin.com/JFJePeKA

**Comment by storm345** [comment]
Since this is closed I'm guessing you managed to resolve the issue?
